// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PBDUserAmulet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PBDUserAmulet.proto</summary>
public static partial class PBDUserAmuletReflection {

  #region Descriptor
  /// <summary>File descriptor for PBDUserAmulet.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PBDUserAmuletReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNQQkRVc2VyQW11bGV0LnByb3RvIu4CCg1QQkRVc2VyQW11bGV0EgoKAmlk",
          "GAEgASgEEg4KBnVzZXJJZBgCIAEoBBIQCghhbXVsZXRJZBgDIAEoDRISCgph",
          "bXVsZXRUeXBlGAQgASgREg4KBnN0YXR1cxgFIAEoERIMCgRoZXJvGAYgASgE",
          "EhcKD3N0cmVuZ3RoZW5MZXZlbBgHIAEoDRIWCg5wcm9tb3Rpb25MZXZlbBgI",
          "IAEoDRIWCg5wcm9tb3Rpb25TdGFnZRgJIAEoDRIWCg50cmFuc211dGVMZXZl",
          "bBgKIAEoDRIWCg50cmFuc211dGVTdGFnZRgLIAEoDRIUCgx0cmFuc211dGVF",
          "eHAYDCABKA0SOAoNdHJhbnNtdXRlQ29zdBgNIAMoCzIhLlBCRFVzZXJBbXVs",
          "ZXQuVHJhbnNtdXRlQ29zdEVudHJ5GjQKElRyYW5zbXV0ZUNvc3RFbnRyeRIL",
          "CgNrZXkYASABKA0SDQoFdmFsdWUYAiABKA06AjgBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PBDUserAmulet), global::PBDUserAmulet.Parser, new[]{ "Id", "UserId", "AmuletId", "AmuletType", "Status", "Hero", "StrengthenLevel", "PromotionLevel", "PromotionStage", "TransmuteLevel", "TransmuteStage", "TransmuteExp", "TransmuteCost" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PBDUserAmulet : pb::IMessage<PBDUserAmulet>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PBDUserAmulet> _parser = new pb::MessageParser<PBDUserAmulet>(() => new PBDUserAmulet());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PBDUserAmulet> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PBDUserAmuletReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PBDUserAmulet() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PBDUserAmulet(PBDUserAmulet other) : this() {
    id_ = other.id_;
    userId_ = other.userId_;
    amuletId_ = other.amuletId_;
    amuletType_ = other.amuletType_;
    status_ = other.status_;
    hero_ = other.hero_;
    strengthenLevel_ = other.strengthenLevel_;
    promotionLevel_ = other.promotionLevel_;
    promotionStage_ = other.promotionStage_;
    transmuteLevel_ = other.transmuteLevel_;
    transmuteStage_ = other.transmuteStage_;
    transmuteExp_ = other.transmuteExp_;
    transmuteCost_ = other.transmuteCost_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PBDUserAmulet Clone() {
    return new PBDUserAmulet(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private ulong id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 2;
  private ulong userId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "amuletId" field.</summary>
  public const int AmuletIdFieldNumber = 3;
  private uint amuletId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AmuletId {
    get { return amuletId_; }
    set {
      amuletId_ = value;
    }
  }

  /// <summary>Field number for the "amuletType" field.</summary>
  public const int AmuletTypeFieldNumber = 4;
  private int amuletType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AmuletType {
    get { return amuletType_; }
    set {
      amuletType_ = value;
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 5;
  private int status_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "hero" field.</summary>
  public const int HeroFieldNumber = 6;
  private ulong hero_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Hero {
    get { return hero_; }
    set {
      hero_ = value;
    }
  }

  /// <summary>Field number for the "strengthenLevel" field.</summary>
  public const int StrengthenLevelFieldNumber = 7;
  private uint strengthenLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StrengthenLevel {
    get { return strengthenLevel_; }
    set {
      strengthenLevel_ = value;
    }
  }

  /// <summary>Field number for the "promotionLevel" field.</summary>
  public const int PromotionLevelFieldNumber = 8;
  private uint promotionLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PromotionLevel {
    get { return promotionLevel_; }
    set {
      promotionLevel_ = value;
    }
  }

  /// <summary>Field number for the "promotionStage" field.</summary>
  public const int PromotionStageFieldNumber = 9;
  private uint promotionStage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PromotionStage {
    get { return promotionStage_; }
    set {
      promotionStage_ = value;
    }
  }

  /// <summary>Field number for the "transmuteLevel" field.</summary>
  public const int TransmuteLevelFieldNumber = 10;
  private uint transmuteLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TransmuteLevel {
    get { return transmuteLevel_; }
    set {
      transmuteLevel_ = value;
    }
  }

  /// <summary>Field number for the "transmuteStage" field.</summary>
  public const int TransmuteStageFieldNumber = 11;
  private uint transmuteStage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TransmuteStage {
    get { return transmuteStage_; }
    set {
      transmuteStage_ = value;
    }
  }

  /// <summary>Field number for the "transmuteExp" field.</summary>
  public const int TransmuteExpFieldNumber = 12;
  private uint transmuteExp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TransmuteExp {
    get { return transmuteExp_; }
    set {
      transmuteExp_ = value;
    }
  }

  /// <summary>Field number for the "transmuteCost" field.</summary>
  public const int TransmuteCostFieldNumber = 13;
  private static readonly pbc::MapField<uint, uint>.Codec _map_transmuteCost_codec
      = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 106);
  private readonly pbc::MapField<uint, uint> transmuteCost_ = new pbc::MapField<uint, uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<uint, uint> TransmuteCost {
    get { return transmuteCost_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PBDUserAmulet);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PBDUserAmulet other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (UserId != other.UserId) return false;
    if (AmuletId != other.AmuletId) return false;
    if (AmuletType != other.AmuletType) return false;
    if (Status != other.Status) return false;
    if (Hero != other.Hero) return false;
    if (StrengthenLevel != other.StrengthenLevel) return false;
    if (PromotionLevel != other.PromotionLevel) return false;
    if (PromotionStage != other.PromotionStage) return false;
    if (TransmuteLevel != other.TransmuteLevel) return false;
    if (TransmuteStage != other.TransmuteStage) return false;
    if (TransmuteExp != other.TransmuteExp) return false;
    if (!TransmuteCost.Equals(other.TransmuteCost)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0UL) hash ^= Id.GetHashCode();
    if (UserId != 0UL) hash ^= UserId.GetHashCode();
    if (AmuletId != 0) hash ^= AmuletId.GetHashCode();
    if (AmuletType != 0) hash ^= AmuletType.GetHashCode();
    if (Status != 0) hash ^= Status.GetHashCode();
    if (Hero != 0UL) hash ^= Hero.GetHashCode();
    if (StrengthenLevel != 0) hash ^= StrengthenLevel.GetHashCode();
    if (PromotionLevel != 0) hash ^= PromotionLevel.GetHashCode();
    if (PromotionStage != 0) hash ^= PromotionStage.GetHashCode();
    if (TransmuteLevel != 0) hash ^= TransmuteLevel.GetHashCode();
    if (TransmuteStage != 0) hash ^= TransmuteStage.GetHashCode();
    if (TransmuteExp != 0) hash ^= TransmuteExp.GetHashCode();
    hash ^= TransmuteCost.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Id);
    }
    if (UserId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(UserId);
    }
    if (AmuletId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(AmuletId);
    }
    if (AmuletType != 0) {
      output.WriteRawTag(32);
      output.WriteSInt32(AmuletType);
    }
    if (Status != 0) {
      output.WriteRawTag(40);
      output.WriteSInt32(Status);
    }
    if (Hero != 0UL) {
      output.WriteRawTag(48);
      output.WriteUInt64(Hero);
    }
    if (StrengthenLevel != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(StrengthenLevel);
    }
    if (PromotionLevel != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(PromotionLevel);
    }
    if (PromotionStage != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(PromotionStage);
    }
    if (TransmuteLevel != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(TransmuteLevel);
    }
    if (TransmuteStage != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(TransmuteStage);
    }
    if (TransmuteExp != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(TransmuteExp);
    }
    transmuteCost_.WriteTo(output, _map_transmuteCost_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Id);
    }
    if (UserId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(UserId);
    }
    if (AmuletId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(AmuletId);
    }
    if (AmuletType != 0) {
      output.WriteRawTag(32);
      output.WriteSInt32(AmuletType);
    }
    if (Status != 0) {
      output.WriteRawTag(40);
      output.WriteSInt32(Status);
    }
    if (Hero != 0UL) {
      output.WriteRawTag(48);
      output.WriteUInt64(Hero);
    }
    if (StrengthenLevel != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(StrengthenLevel);
    }
    if (PromotionLevel != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(PromotionLevel);
    }
    if (PromotionStage != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(PromotionStage);
    }
    if (TransmuteLevel != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(TransmuteLevel);
    }
    if (TransmuteStage != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(TransmuteStage);
    }
    if (TransmuteExp != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(TransmuteExp);
    }
    transmuteCost_.WriteTo(ref output, _map_transmuteCost_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
    }
    if (UserId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
    }
    if (AmuletId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AmuletId);
    }
    if (AmuletType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeSInt32Size(AmuletType);
    }
    if (Status != 0) {
      size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Status);
    }
    if (Hero != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Hero);
    }
    if (StrengthenLevel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StrengthenLevel);
    }
    if (PromotionLevel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PromotionLevel);
    }
    if (PromotionStage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PromotionStage);
    }
    if (TransmuteLevel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TransmuteLevel);
    }
    if (TransmuteStage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TransmuteStage);
    }
    if (TransmuteExp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TransmuteExp);
    }
    size += transmuteCost_.CalculateSize(_map_transmuteCost_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PBDUserAmulet other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0UL) {
      Id = other.Id;
    }
    if (other.UserId != 0UL) {
      UserId = other.UserId;
    }
    if (other.AmuletId != 0) {
      AmuletId = other.AmuletId;
    }
    if (other.AmuletType != 0) {
      AmuletType = other.AmuletType;
    }
    if (other.Status != 0) {
      Status = other.Status;
    }
    if (other.Hero != 0UL) {
      Hero = other.Hero;
    }
    if (other.StrengthenLevel != 0) {
      StrengthenLevel = other.StrengthenLevel;
    }
    if (other.PromotionLevel != 0) {
      PromotionLevel = other.PromotionLevel;
    }
    if (other.PromotionStage != 0) {
      PromotionStage = other.PromotionStage;
    }
    if (other.TransmuteLevel != 0) {
      TransmuteLevel = other.TransmuteLevel;
    }
    if (other.TransmuteStage != 0) {
      TransmuteStage = other.TransmuteStage;
    }
    if (other.TransmuteExp != 0) {
      TransmuteExp = other.TransmuteExp;
    }
    transmuteCost_.Add(other.transmuteCost_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadUInt64();
          break;
        }
        case 16: {
          UserId = input.ReadUInt64();
          break;
        }
        case 24: {
          AmuletId = input.ReadUInt32();
          break;
        }
        case 32: {
          AmuletType = input.ReadSInt32();
          break;
        }
        case 40: {
          Status = input.ReadSInt32();
          break;
        }
        case 48: {
          Hero = input.ReadUInt64();
          break;
        }
        case 56: {
          StrengthenLevel = input.ReadUInt32();
          break;
        }
        case 64: {
          PromotionLevel = input.ReadUInt32();
          break;
        }
        case 72: {
          PromotionStage = input.ReadUInt32();
          break;
        }
        case 80: {
          TransmuteLevel = input.ReadUInt32();
          break;
        }
        case 88: {
          TransmuteStage = input.ReadUInt32();
          break;
        }
        case 96: {
          TransmuteExp = input.ReadUInt32();
          break;
        }
        case 106: {
          transmuteCost_.AddEntriesFrom(input, _map_transmuteCost_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadUInt64();
          break;
        }
        case 16: {
          UserId = input.ReadUInt64();
          break;
        }
        case 24: {
          AmuletId = input.ReadUInt32();
          break;
        }
        case 32: {
          AmuletType = input.ReadSInt32();
          break;
        }
        case 40: {
          Status = input.ReadSInt32();
          break;
        }
        case 48: {
          Hero = input.ReadUInt64();
          break;
        }
        case 56: {
          StrengthenLevel = input.ReadUInt32();
          break;
        }
        case 64: {
          PromotionLevel = input.ReadUInt32();
          break;
        }
        case 72: {
          PromotionStage = input.ReadUInt32();
          break;
        }
        case 80: {
          TransmuteLevel = input.ReadUInt32();
          break;
        }
        case 88: {
          TransmuteStage = input.ReadUInt32();
          break;
        }
        case 96: {
          TransmuteExp = input.ReadUInt32();
          break;
        }
        case 106: {
          transmuteCost_.AddEntriesFrom(ref input, _map_transmuteCost_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
